      - name: Build and deploy to monday code
        env:
          MONDAY_TOKEN: ${{ secrets.MONDAY_TOKEN }}
        run: |
          mapps init -t "$MONDAY_TOKEN"
          cd monday-assignment-admin
          npm ci
          npm run build
          cd dist
          mapps code:push --client-side --appVersionId 18198232
